let roomInfo = [
    {
        roomid: 0,
        roomType: "standard",
        roomName: "Garden Standard Chalet",
        price: "LKR 20,000",
        size: 28,
        capacity: 2,
        capacityString: "2 Adults",
        bed: "1 queen bed",
        bedCount: 1,
        amenities: "Free WiFi, Air Conditioning, Smart TV, Rain Shower",
        Cancellation: "Free up to 24 hours before arrival",
        freePerks: "Breakfast for two, tea estate shuttle",
        features: ["wifi", "tv", "gardenview", "hotwater"],
        description: "A calm entry-level chalet facing the garden, ideal for couples who want a quiet stay close to the pool and restaurant.",
        pic1: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img3.jpg"
    },
    {
        roomid: 1,
        roomType: "deluxe",
        roomName: "Balcony Deluxe Triple",
        price: "LKR 25,000",
        size: 33,
        capacity: 3,
        capacityString: "3 Adults",
        bed: "1 king bed and 1 single bed",
        bedCount: 2,
        amenities: "Free WiFi, Balcony, Smart TV, Mini Fridge",
        Cancellation: "Free up to 24 hours before arrival",
        freePerks: "Breakfast, welcome drink, late checkout on request",
        features: ["wifi", "tv", "gardenview", "meals"],
        description: "A brighter deluxe room with extra floor space and a private balcony overlooking the landscaped courtyard.",
        pic1: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img3.jpg"
    },
    {
        roomid: 2,
        roomType: "deluxe",
        roomName: "Poolside Deluxe Quad",
        price: "LKR 32,000",
        size: 39,
        capacity: 4,
        capacityString: "4 Adults",
        bed: "2 queen beds",
        bedCount: 2,
        amenities: "Free WiFi, Smart TV, Pool Access, Work Desk",
        Cancellation: "Free up to 48 hours before arrival",
        freePerks: "Breakfast, pool towels, coffee setup",
        features: ["wifi", "tv", "poolaccess", "towels"],
        description: "A pool-facing deluxe room designed for small groups who want quick access to the shared swimming area.",
        pic1: "assets/img/hotel-rooms/room 0/img3.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img1.jpg"
    },
    {
        roomid: 3,
        roomType: "family",
        roomName: "Family Garden Loft",
        price: "LKR 42,000",
        size: 48,
        capacity: 5,
        capacityString: "5 Adults",
        bed: "1 king bed, 2 single beds, 1 sofa bed",
        bedCount: 4,
        amenities: "Free WiFi, TV, Family Lounge, Hot Water",
        Cancellation: "Free up to 48 hours before arrival",
        freePerks: "Breakfast, kids snack tray, garden seating",
        features: ["wifi", "tv", "gardenview", "hotwater"],
        description: "A split-level family stay with a lounge corner and enough room for parents, kids, and extra luggage.",
        pic1: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img3.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img2.jpg"
    },
    {
        roomid: 4,
        roomType: "family",
        roomName: "Tea Estate Family Suite",
        price: "LKR 49,000",
        size: 54,
        capacity: 6,
        capacityString: "6 Adults",
        bed: "2 queen beds and 2 single beds",
        bedCount: 4,
        amenities: "Free WiFi, TV, Bathtub, Dining Nook",
        Cancellation: "Free up to 72 hours before arrival",
        freePerks: "Breakfast, evening tea platter, estate-view balcony",
        features: ["wifi", "tv", "seaview", "meals"],
        description: "A larger family option with four proper beds and enough flexibility for a longer group stay.",
        pic1: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img3.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img1.jpg"
    },
    {
        roomid: 5,
        roomType: "suite",
        roomName: "Private Jacuzzi Suite",
        price: "LKR 68,000",
        size: 61,
        capacity: 2,
        capacityString: "2 Adults",
        bed: "1 extra-large king bed",
        bedCount: 1,
        amenities: "Private Jacuzzi, Smart TV, Free WiFi, Butler Call",
        Cancellation: "Free up to 72 hours before arrival",
        freePerks: "Floating breakfast, private check-in, flower setup",
        features: ["wifi", "tv", "roomservice", "seaview"],
        description: "A premium romantic suite with a private jacuzzi and more privacy for couples celebrating special occasions.",
        pic1: "assets/img/hotel-rooms/room 0/img3.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img2.jpg"
    },
    {
        roomid: 6,
        roomType: "suite",
        roomName: "Panorama Ocean Suite",
        price: "LKR 74,000",
        size: 66,
        capacity: 4,
        capacityString: "4 Adults",
        bed: "2 king beds",
        bedCount: 2,
        amenities: "Ocean View, Lounge Area, Free WiFi, Smart TV",
        Cancellation: "Free up to 72 hours before arrival",
        freePerks: "Breakfast, sunset mocktails, reserved cabana",
        features: ["wifi", "tv", "seaview", "poolaccess"],
        description: "An elevated suite for families or friends who want a premium stay with wide views and a spacious sitting area.",
        pic1: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img3.jpg"
    },
    {
        roomid: 7,
        roomType: "dorm",
        roomName: "Group Dorm Pavilion",
        price: "LKR 55,000",
        size: 70,
        capacity: 8,
        capacityString: "8 Adults",
        bed: "4 bunk beds",
        bedCount: 4,
        amenities: "Shared Lounge, Lockers, Free WiFi, Hot Water",
        Cancellation: "Free up to 72 hours before arrival",
        freePerks: "Group breakfast, luggage room, bonfire corner",
        features: ["wifi", "locker", "hotwater", "parking"],
        description: "A practical group stay for excursions, friend trips, and team outings with simple shared comforts.",
        pic1: "assets/img/hotel-rooms/room 0/img2.jpg",
        pic2: "assets/img/hotel-rooms/room 0/img1.jpg",
        pic3: "assets/img/hotel-rooms/room 0/img3.jpg"
    }
];
